version: '3.7'

services:
  nginx:
    image: nginx:1
    volumes:
      - "./tongan:/usr/share/nginx/html:ro"
    networks:
      - nginx-bridge
    environment:
      VIRTUAL_HOST: "tongan-puntiunn.ithuan.tw"
      LETSENCRYPT_HOST: "tongan-puntiunn.ithuan.tw"
      LETSENCRYPT_EMAIL: "ithuan@ithuan.tw"
    restart: always

networks:
  nginx-bridge:
    name: nginx-bridge
